In [2]:
import numpy as np
import pandas as pd

In [4]:
x = pd.read_csv(
    "../../Data/new/widsdatathon2025/TRAIN/TRAIN_FUNCTIONAL_CONNECTOME_MATRICES_new_36p_Pearson.csv"
)

In [3]:
x.iloc[:, 1:].head()

,0throw_1thcolumn,0throw_2thcolumn,0throw_3thcolumn,0throw_4thcolumn,0throw_5thcolumn,0throw_6thcolumn,0throw_7thcolumn,0throw_8thcolumn,0throw_9thcolumn,0throw_10thcolumn,...,195throw_196thcolumn,195throw_197thcolumn,195throw_198thcolumn,195throw_199thcolumn,196throw_197thcolumn,196throw_198thcolumn,196throw_199thcolumn,197throw_198thcolumn,197throw_199thcolumn,198throw_199thcolumn
0,0.093473,0.146902,0.067893,0.015141,0.070221,0.063997,0.055382,-0.035335,0.068583,0.029271,...,0.003404,-0.010359,-0.050968,-0.014365,0.128066,0.112646,-0.058980,0.028228,0.133582,0.143372
1,0.029580,0.179323,0.112933,0.038291,0.104899,0.064250,0.008488,0.077505,-0.004750,-0.035073,...,-0.008409,-0.008479,0.020891,0.017754,0.094040,0.035141,0.032537,0.075007,0.115350,0.138200
2,-0.051580,0.139734,0.068295,0.046991,0.111085,0.026978,0.151377,0.021198,0.083721,-0.014275,...,0.053245,-0.028003,0.028773,0.024556,0.166343,0.058925,0.035485,0.063661,0.042862,0.162162
3,0.016273,0.204702,0.115980,0.043103,0.056431,0.057615,0.055773,0.075030,0.001033,-0.064031,...,-0.023918,-0.005356,0.018607,0.016193,0.072955,0.130135,0.056120,0.084784,0.114148,0.190584
4,0.065771,0.098714,0.097604,0.112988,0.071139,0.085607,0.019392,-0.036403,-0.020375,0.005426,...,0.066439,-0.076680,-0.047530,-0.031443,0.221213,0.007343,0.005763,0.083820,0.079582,0.067269

# .

In [5]:
cols = x.columns[1:]
feats = x[cols].to_numpy()

In [6]:
feats.shape

(1213, 19900)

In [7]:
abs_values = np.abs(feats)

In [8]:
min_ = np.min(abs_values, axis=0, keepdims=True)
max_ = np.max(abs_values, axis=0, keepdims=True)

In [9]:
abs_values = (abs_values - min_) / (max_ - min_)

In [10]:
normalized = abs_values * np.sign(feats)

In [11]:
np.min(normalized), np.max(normalized)

(np.float64(-1.0), np.float64(1.0))

In [12]:
normalized[1, :20]

array([ 0.74560623,  0.63529656,  0.56071165,  0.56532031,  0.44925374,
        0.4943708 ,  0.133775  , -0.10555901,  0.14074565,  0.33301492,
        0.08533612, -0.54323101, -0.72777517,  0.02602139, -0.72802227,
       -0.24242715,  0.14206937,  0.02743119,  0.26264707, -0.29057   ])

# .

In [13]:
df = pd.DataFrame(normalized, columns=x.columns[1:])

df.head()

,0throw_1thcolumn,0throw_2thcolumn,0throw_3thcolumn,0throw_4thcolumn,0throw_5thcolumn,0throw_6thcolumn,0throw_7thcolumn,0throw_8thcolumn,0throw_9thcolumn,0throw_10thcolumn,...,195throw_196thcolumn,195throw_197thcolumn,195throw_198thcolumn,195throw_199thcolumn,196throw_197thcolumn,196throw_198thcolumn,196throw_199thcolumn,197throw_198thcolumn,197throw_199thcolumn,198throw_199thcolumn
0,0.270222,0.580746,0.485892,0.066911,0.631380,0.352300,0.567586,-0.096635,0.615247,0.567086,...,0.335125,0.640509,0.670238,0.277060,0.341693,0.484909,0.019694,0.611801,0.514553,0.403950
1,0.745606,0.635297,0.560712,0.565320,0.449254,0.494371,0.133775,-0.105559,0.140746,0.333015,...,0.324024,-0.022980,0.000259,-0.144654,0.509713,0.396639,0.201872,0.662280,0.604821,0.556749
2,-0.141502,0.503933,0.294476,0.728077,0.859708,0.497574,0.712298,0.238339,0.609023,0.456516,...,0.510477,-0.033611,-0.059555,0.112554,0.462574,0.337501,0.471778,0.501214,0.557432,0.690832
3,0.242024,0.829234,0.744090,0.655015,0.773632,0.729741,0.583713,0.512699,0.621283,0.312770,...,0.153921,-0.287094,0.334107,-0.027872,0.489196,0.684274,0.260865,0.368633,0.479496,0.617687
4,0.275549,0.675102,0.702433,0.640819,0.822982,0.665804,0.295784,0.447255,0.351740,0.399588,...,-0.245542,0.010908,-0.191272,-0.732648,0.553789,-0.248176,0.254205,0.053999,0.114523,0.119353

# function

In [14]:
def normalize_df(df):
    # Extract numeric columns (excluding the first column)
    numeric_cols = df.columns[1:]
    x = df[numeric_cols].to_numpy()

    # Min-max normalization preserving sign
    abs_values = np.abs(x)
    min_ = np.min(abs_values, axis=0, keepdims=True)
    max_ = np.max(abs_values, axis=0, keepdims=True)
    abs_values = (abs_values - min_) / (max_ - min_)

    # Modify DataFrame in place
    df.loc[:, numeric_cols] = abs_values * np.sign(x)

    return df  # Returns modified DataFrame

In [15]:
normed = normalize_df(x)

In [16]:
normed.head()

,participant_id,0throw_1thcolumn,0throw_2thcolumn,0throw_3thcolumn,0throw_4thcolumn,0throw_5thcolumn,0throw_6thcolumn,0throw_7thcolumn,0throw_8thcolumn,0throw_9thcolumn,...,195throw_196thcolumn,195throw_197thcolumn,195throw_198thcolumn,195throw_199thcolumn,196throw_197thcolumn,196throw_198thcolumn,196throw_199thcolumn,197throw_198thcolumn,197throw_199thcolumn,198throw_199thcolumn
0,70z8Q2xdTXM3,0.270222,0.580746,0.485892,0.066911,0.631380,0.352300,0.567586,-0.096635,0.615247,...,0.335125,0.640509,0.670238,0.277060,0.341693,0.484909,0.019694,0.611801,0.514553,0.403950
1,WHWymJu6zNZi,0.745606,0.635297,0.560712,0.565320,0.449254,0.494371,0.133775,-0.105559,0.140746,...,0.324024,-0.022980,0.000259,-0.144654,0.509713,0.396639,0.201872,0.662280,0.604821,0.556749
2,4PAQp1M6EyAo,-0.141502,0.503933,0.294476,0.728077,0.859708,0.497574,0.712298,0.238339,0.609023,...,0.510477,-0.033611,-0.059555,0.112554,0.462574,0.337501,0.471778,0.501214,0.557432,0.690832
3,obEacy4Of68I,0.242024,0.829234,0.744090,0.655015,0.773632,0.729741,0.583713,0.512699,0.621283,...,0.153921,-0.287094,0.334107,-0.027872,0.489196,0.684274,0.260865,0.368633,0.479496,0.617687
4,s7WzzDcmDOhF,0.275549,0.675102,0.702433,0.640819,0.822982,0.665804,0.295784,0.447255,0.351740,...,-0.245542,0.010908,-0.191272,-0.732648,0.553789,-0.248176,0.254205,0.053999,0.114523,0.119353

In [17]:
def normalize_two_dfs(df1, df2):
    # Extract numeric columns (excluding the first column)
    numeric_cols = df1.columns[1:]  # Assuming both DataFrames have the same structure

    # Stack both DataFrames' numeric values for global normalization
    combined_x = np.vstack([df1[numeric_cols].to_numpy(), df2[numeric_cols].to_numpy()])

    # Compute global min and max
    abs_values = np.abs(combined_x)
    min_ = np.min(abs_values, axis=0, keepdims=True)
    max_ = np.max(abs_values, axis=0, keepdims=True)
    
    # Perform min-max normalization while preserving sign
    normalized_values = (abs_values - min_) / (max_ - min_) * np.sign(combined_x)

    # Split back into two DataFrames
    df1.loc[:, numeric_cols] = normalized_values[:len(df1)]
    df2.loc[:, numeric_cols] = normalized_values[len(df1):]

    return df1, df2  # Returns both normalized DataFrames

In [19]:
train, test = pd.read_csv(
    "../../Data/new/widsdatathon2025/TRAIN/TRAIN_FUNCTIONAL_CONNECTOME_MATRICES_new_36p_Pearson.csv"
), pd.read_csv("../../Data/new/widsdatathon2025/TEST/TEST_FUNCTIONAL_CONNECTOME_MATRICES.csv")

In [20]:
normed_train, normed_test = normalize_two_dfs(train, test)

In [21]:
normed_train.head()

,participant_id,0throw_1thcolumn,0throw_2thcolumn,0throw_3thcolumn,0throw_4thcolumn,0throw_5thcolumn,0throw_6thcolumn,0throw_7thcolumn,0throw_8thcolumn,0throw_9thcolumn,...,195throw_196thcolumn,195throw_197thcolumn,195throw_198thcolumn,195throw_199thcolumn,196throw_197thcolumn,196throw_198thcolumn,196throw_199thcolumn,197throw_198thcolumn,197throw_199thcolumn,198throw_199thcolumn
0,70z8Q2xdTXM3,0.270399,0.580746,0.485892,0.064059,0.617299,0.337467,0.550230,-0.087434,0.579197,...,0.305246,0.583610,0.540900,0.228036,0.343643,0.485184,0.019701,0.614717,0.524420,0.404290
1,WHWymJu6zNZi,0.745668,0.635297,0.560712,0.541223,0.439375,0.473556,0.129684,-0.095509,0.132499,...,0.295154,-0.021363,0.000563,-0.119118,0.511165,0.396962,0.201877,0.664817,0.612853,0.557002
2,4PAQp1M6EyAo,-0.141711,0.503933,0.294476,0.697041,0.840358,0.476623,0.690517,0.215647,0.573338,...,0.464666,-0.031043,-0.048386,0.092712,0.464166,0.337855,0.471782,0.504960,0.566427,0.691008
3,obEacy4Of68I,0.242208,0.829234,0.744090,0.627094,0.756269,0.699015,0.565864,0.463884,0.584879,...,0.140506,-0.261833,0.269811,-0.023052,0.490709,0.684443,0.260870,0.373375,0.490076,0.617905
4,s7WzzDcmDOhF,0.275725,0.675102,0.702433,0.613503,0.804479,0.637771,0.286740,0.404671,0.331130,...,-0.223803,0.010372,-0.154615,-0.602806,0.555110,-0.248578,0.254210,0.061103,0.132521,0.119855

In [22]:
normed_test.head()

,participant_id,0throw_1thcolumn,0throw_2thcolumn,0throw_3thcolumn,0throw_4thcolumn,0throw_5thcolumn,0throw_6thcolumn,0throw_7thcolumn,0throw_8thcolumn,0throw_9thcolumn,...,195throw_196thcolumn,195throw_197thcolumn,195throw_198thcolumn,195throw_199thcolumn,196throw_197thcolumn,196throw_198thcolumn,196throw_199thcolumn,197throw_198thcolumn,197throw_199thcolumn,198throw_199thcolumn
0,Cfwaf5FX7jWK,0.665269,0.786008,0.629912,0.571596,0.756816,0.834951,0.785671,0.439002,0.603705,...,0.109113,-0.080147,-0.112746,-0.035289,0.500307,0.404156,-0.015204,0.728375,0.623918,0.615181
1,vhGrzmvA3Hjq,0.518820,0.398501,0.455240,0.395056,0.582186,0.370295,0.442388,0.341152,0.443344,...,0.268648,-0.001063,0.106298,0.040809,0.773208,0.353462,0.865709,0.505250,0.622880,0.387470
2,ULliyEXjy4OV,0.169292,0.428437,-0.098085,0.213280,0.091299,0.018532,0.412206,0.076936,0.415742,...,0.069627,0.034699,-0.072661,0.144986,0.647908,0.597701,0.635925,0.661952,0.678780,0.831323
3,LZfeAb1xMtql,0.162000,0.857543,0.470499,0.514128,0.619466,0.685745,0.542278,0.388654,0.515506,...,0.062658,-0.350891,0.155848,-0.322303,0.727458,0.686660,0.733794,0.651472,0.760400,0.600308
4,EnFOUv0YK1RG,0.153677,0.633297,0.575747,0.395263,0.464511,0.484715,0.488523,0.251631,0.328348,...,0.428369,0.003280,0.371870,0.425030,0.540083,0.623086,0.539733,0.320658,0.165316,0.597570

In [23]:
normed_train.to_csv('../../Data/new/preprocessed/train/connectome_matrices.csv', index=False)
normed_test.to_csv('../../Data/new/preprocessed/test/connectome_matrices.csv', index=False)