In [1]:
import numpy as np
import pandas as pd

In [2]:
x = pd.read_csv(
    "../../Data/widsdatathon2025/TRAIN/TRAIN_FUNCTIONAL_CONNECTOME_MATRICES.csv"
)

In [3]:
x.iloc[:, 1:].head()

,0throw_1thcolumn,0throw_2thcolumn,0throw_3thcolumn,0throw_4thcolumn,0throw_5thcolumn,0throw_6thcolumn,0throw_7thcolumn,0throw_8thcolumn,0throw_9thcolumn,0throw_10thcolumn,...,195throw_196thcolumn,195throw_197thcolumn,195throw_198thcolumn,195throw_199thcolumn,196throw_197thcolumn,196throw_198thcolumn,196throw_199thcolumn,197throw_198thcolumn,197throw_199thcolumn,198throw_199thcolumn
0,0.093473,0.146902,0.067893,0.015141,0.070221,0.063997,0.055382,-0.035335,0.068583,0.029271,...,0.003404,-0.010359,-0.050968,-0.014365,0.128066,0.112646,-0.058980,0.028228,0.133582,0.143372
1,0.029580,0.179323,0.112933,0.038291,0.104899,0.064250,0.008488,0.077505,-0.004750,-0.035073,...,-0.008409,-0.008479,0.020891,0.017754,0.094040,0.035141,0.032537,0.075007,0.115350,0.138200
2,-0.051580,0.139734,0.068295,0.046991,0.111085,0.026978,0.151377,0.021198,0.083721,-0.014275,...,0.053245,-0.028003,0.028773,0.024556,0.166343,0.058925,0.035485,0.063661,0.042862,0.162162
3,0.016273,0.204702,0.115980,0.043103,0.056431,0.057615,0.055773,0.075030,0.001033,-0.064031,...,-0.023918,-0.005356,0.018607,0.016193,0.072955,0.130135,0.056120,0.084784,0.114148,0.190584
4,0.065771,0.098714,0.097604,0.112988,0.071139,0.085607,0.019392,-0.036403,-0.020375,0.005426,...,0.066439,-0.076680,-0.047530,-0.031443,0.221213,0.007343,0.005763,0.083820,0.079582,0.067269

# .

In [4]:
cols = x.columns[1:]
feats = x[cols].to_numpy()

In [5]:
feats.shape

(1213, 19900)

In [6]:
abs_values = np.abs(feats)

In [7]:
min_ = np.min(abs_values, axis=0, keepdims=True)
max_ = np.max(abs_values, axis=0, keepdims=True)

In [8]:
abs_values = (abs_values - min_) / (max_ - min_)

In [9]:
normalized = abs_values * np.sign(feats)

In [10]:
np.min(normalized), np.max(normalized)

(np.float64(-1.0), np.float64(1.0))

In [11]:
normalized[1, :20]

array([ 0.09158499,  0.45856789,  0.40541966,  0.20102486,  0.33020227,
        0.2023445 ,  0.03128758,  0.46038585, -0.03258008, -0.23591285,
        0.29675868, -0.53422666, -0.17546223,  0.1058503 , -0.41284779,
       -0.11788568, -0.51231696,  0.18005601,  0.73328483,  0.39725543])

# .

In [ ]:
df = pd.DataFrame(normalized, columns=x.columns[1:])

df.head()

,0,1,2,3,4,5,6,7,8,9,...,19890,19891,19892,19893,19894,19895,19896,19897,19898,19899
0,0.290397,0.375599,0.243601,0.078965,0.220947,0.201545,0.204984,-0.209476,0.471748,0.196819,...,0.017491,-0.056561,-0.282276,-0.074811,0.340933,0.492447,-0.183119,0.081080,0.500005,0.346055
1,0.091585,0.458568,0.405420,0.201025,0.330202,0.202345,0.031288,0.460386,-0.032580,-0.235913,...,-0.043206,-0.046295,0.115698,0.092459,0.250349,0.153625,0.101020,0.215444,0.431761,0.333571
2,-0.160041,0.357255,0.245047,0.246895,0.349688,0.084630,0.560551,0.125355,0.575894,-0.095795,...,0.273589,-0.152896,0.159352,0.127888,0.442831,0.257597,0.110174,0.182854,0.160435,0.391409
3,0.050181,0.523513,0.416366,0.226394,0.177503,0.181388,0.206432,0.445657,0.007003,-0.430997,...,-0.122898,-0.029241,0.103050,0.084332,0.194217,0.568904,0.174241,0.243526,0.427264,0.460011
4,0.204197,0.252280,0.350346,0.594874,0.223840,0.269795,0.071676,-0.215828,-0.140078,0.036180,...,0.341384,-0.418666,-0.263235,-0.163755,0.588902,0.032102,0.017893,0.240756,0.297882,0.162367

# function

In [14]:
def normalize_df(df):
    # Extract numeric columns (excluding the first column)
    numeric_cols = df.columns[1:]
    x = df[numeric_cols].to_numpy()

    # Min-max normalization preserving sign
    abs_values = np.abs(x)
    min_ = np.min(abs_values, axis=0, keepdims=True)
    max_ = np.max(abs_values, axis=0, keepdims=True)
    abs_values = (abs_values - min_) / (max_ - min_)

    # Modify DataFrame in place
    df.loc[:, numeric_cols] = abs_values * np.sign(x)

    return df  # Returns modified DataFrame

In [15]:
normed = normalize_df(x)

In [16]:
normed.head()

,participant_id,0throw_1thcolumn,0throw_2thcolumn,0throw_3thcolumn,0throw_4thcolumn,0throw_5thcolumn,0throw_6thcolumn,0throw_7thcolumn,0throw_8thcolumn,0throw_9thcolumn,...,195throw_196thcolumn,195throw_197thcolumn,195throw_198thcolumn,195throw_199thcolumn,196throw_197thcolumn,196throw_198thcolumn,196throw_199thcolumn,197throw_198thcolumn,197throw_199thcolumn,198throw_199thcolumn
0,70z8Q2xdTXM3,0.290397,0.375599,0.243601,0.078965,0.220947,0.201545,0.204984,-0.209476,0.471748,...,0.017491,-0.056561,-0.282276,-0.074811,0.340933,0.492447,-0.183119,0.081080,0.500005,0.346055
1,WHWymJu6zNZi,0.091585,0.458568,0.405420,0.201025,0.330202,0.202345,0.031288,0.460386,-0.032580,...,-0.043206,-0.046295,0.115698,0.092459,0.250349,0.153625,0.101020,0.215444,0.431761,0.333571
2,4PAQp1M6EyAo,-0.160041,0.357255,0.245047,0.246895,0.349688,0.084630,0.560551,0.125355,0.575894,...,0.273589,-0.152896,0.159352,0.127888,0.442831,0.257597,0.110174,0.182854,0.160435,0.391409
3,obEacy4Of68I,0.050181,0.523513,0.416366,0.226394,0.177503,0.181388,0.206432,0.445657,0.007003,...,-0.122898,-0.029241,0.103050,0.084332,0.194217,0.568904,0.174241,0.243526,0.427264,0.460011
4,s7WzzDcmDOhF,0.204197,0.252280,0.350346,0.594874,0.223840,0.269795,0.071676,-0.215828,-0.140078,...,0.341384,-0.418666,-0.263235,-0.163755,0.588902,0.032102,0.017893,0.240756,0.297882,0.162367

In [17]:
def normalize_two_dfs(df1, df2):
    # Extract numeric columns (excluding the first column)
    numeric_cols = df1.columns[1:]  # Assuming both DataFrames have the same structure

    # Stack both DataFrames' numeric values for global normalization
    combined_x = np.vstack([df1[numeric_cols].to_numpy(), df2[numeric_cols].to_numpy()])

    # Compute global min and max
    abs_values = np.abs(combined_x)
    min_ = np.min(abs_values, axis=0, keepdims=True)
    max_ = np.max(abs_values, axis=0, keepdims=True)
    
    # Perform min-max normalization while preserving sign
    normalized_values = (abs_values - min_) / (max_ - min_) * np.sign(combined_x)

    # Split back into two DataFrames
    df1.loc[:, numeric_cols] = normalized_values[:len(df1)]
    df2.loc[:, numeric_cols] = normalized_values[len(df1):]

    return df1, df2  # Returns both normalized DataFrames

In [18]:
train, test = pd.read_csv(
    "../../Data/widsdatathon2025/TRAIN/TRAIN_FUNCTIONAL_CONNECTOME_MATRICES.csv"
), pd.read_csv("../../Data/widsdatathon2025/TEST/TEST_FUNCTIONAL_CONNECTOME_MATRICES.csv")

In [19]:
normed_train, normed_test = normalize_two_dfs(train, test)

In [20]:
normed_train.head()

,participant_id,0throw_1thcolumn,0throw_2thcolumn,0throw_3thcolumn,0throw_4thcolumn,0throw_5thcolumn,0throw_6thcolumn,0throw_7thcolumn,0throw_8thcolumn,0throw_9thcolumn,...,195throw_196thcolumn,195throw_197thcolumn,195throw_198thcolumn,195throw_199thcolumn,196throw_197thcolumn,196throw_198thcolumn,196throw_199thcolumn,197throw_198thcolumn,197throw_199thcolumn,198throw_199thcolumn
0,70z8Q2xdTXM3,0.120114,0.162277,0.077418,0.016354,0.076694,0.069311,0.060088,-0.039665,0.075581,...,0.004618,-0.015212,-0.065179,-0.017741,0.146501,0.144346,-0.077084,0.032827,0.162881,0.164357
1,WHWymJu6zNZi,0.038010,0.198124,0.128845,0.041632,0.114618,0.069586,0.009172,0.087176,-0.005220,...,-0.011408,-0.012451,0.026716,0.021926,0.107576,0.045031,0.042524,0.087226,0.140650,0.158428
2,4PAQp1M6EyAo,-0.066280,0.154352,0.077877,0.051132,0.121382,0.029104,0.164318,0.023737,0.092267,...,0.072240,-0.041120,0.036796,0.030327,0.190287,0.075507,0.046378,0.074031,0.052263,0.185898
3,obEacy4Of68I,0.020911,0.226183,0.132323,0.046886,0.061614,0.062379,0.060513,0.084387,0.001122,...,-0.032450,-0.007864,0.023795,0.019999,0.083456,0.166758,0.073347,0.098595,0.139185,0.218480
4,s7WzzDcmDOhF,0.084516,0.108997,0.111342,0.123199,0.077698,0.092782,0.021011,-0.040868,-0.022443,...,0.090140,-0.112596,-0.060783,-0.038833,0.253054,0.009410,0.007532,0.097473,0.097037,0.077115

In [21]:
normed_test.head()

,participant_id,0throw_1thcolumn,0throw_2thcolumn,0throw_3thcolumn,0throw_4thcolumn,0throw_5thcolumn,0throw_6thcolumn,0throw_7thcolumn,0throw_8thcolumn,0throw_9thcolumn,...,195throw_196thcolumn,195throw_197thcolumn,195throw_198thcolumn,195throw_199thcolumn,196throw_197thcolumn,196throw_198thcolumn,196throw_199thcolumn,197throw_198thcolumn,197throw_199thcolumn,198throw_199thcolumn
0,Cfwaf5FX7jWK,0.704801,0.788858,0.636240,0.572410,0.758154,0.836157,0.786503,0.439388,0.603933,...,0.109113,-0.080147,-0.112746,-0.035289,0.508879,0.448687,-0.016469,0.774196,0.683514,0.637075
1,vhGrzmvA3Hjq,0.549649,0.401231,0.459882,0.396205,0.584485,0.374893,0.444552,0.341604,0.443665,...,0.268648,-0.001063,0.106298,0.040809,0.786457,0.392407,0.937728,0.537034,0.682376,0.401260
2,ULliyEXjy4OV,0.179352,0.431177,-0.099281,0.214775,0.096299,0.025699,0.414487,0.077571,0.416079,...,0.069627,0.034699,-0.072661,0.144986,0.659010,0.663557,0.688828,0.703595,0.743616,0.860909
3,LZfeAb1xMtql,0.171627,0.860415,0.475289,0.515051,0.621560,0.688040,0.544055,0.389074,0.515785,...,0.062658,-0.350891,0.155848,-0.322303,0.739922,0.762317,0.794838,0.692455,0.833032,0.621672
4,EnFOUv0YK1RG,0.162809,0.636099,0.581552,0.396412,0.467457,0.488478,0.490508,0.252145,0.328735,...,0.428369,0.003280,0.371870,0.425030,0.549337,0.691739,0.584633,0.340830,0.181106,0.618837

In [23]:
normed_train.to_csv('../../Data/preprocessed/train/connectome_matrices.csv', index=False)
normed_test.to_csv('../../Data/preprocessed/test/connectome_matrices.csv', index=False)